# .github/workflows/flutter_test.yml
name: Flutter Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del código
    - name: Checkout repository
      uses: actions/checkout@v3

    # Paso 2: Configurar Flutter (especificando una versión)
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.0'  # Especifica la versión aquí

    # Paso 3: Instalar dependencias de Flutter
    - name: Install dependencies
      run: flutter pub get

    # Paso 4: Ejecutar pruebas de Flutter específicas
    - name: Run Flutter tests for counter_test
      run: flutter test test/counter_test.dart
